//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6407
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Tools.WindowsInstallerXml.Extensions
{
    using System;
    using System.Reflection;
    using System.Resources;
    using Microsoft.Tools.WindowsInstallerXml;
    
    
    public class ValidationErrorEventArgs : WixErrorEventArgs
    {
        
        private static ResourceManager resourceManager = new ResourceManager("Microsoft.Tools.WindowsInstallerXml.Extensions.Data.Messages", Assembly.GetExecutingAssembly());
        
        public ValidationErrorEventArgs(SourceLineNumberCollection sourceLineNumbers, int id, string resourceName, params object[] messageArgs) : 
                base(sourceLineNumbers, id, resourceName, messageArgs)
        {
        }
        
        public override ResourceManager ResourceManager
        {
            get
            {
                return resourceManager;
            }
        }
    }
    
    public sealed class ValidationErrors
    {
        
        private ValidationErrors()
        {
        }
        
        public static ValidationErrorEventArgs ExampleError()
        {
            return new ValidationErrorEventArgs(null, 6501, "ValidationErrors_ExampleError_1");
        }
    }
    
    public class ValidationWarningEventArgs : WixWarningEventArgs
    {
        
        private static ResourceManager resourceManager = new ResourceManager("Microsoft.Tools.WindowsInstallerXml.Extensions.Data.Messages", Assembly.GetExecutingAssembly());
        
        public ValidationWarningEventArgs(SourceLineNumberCollection sourceLineNumbers, int id, string resourceName, params object[] messageArgs) : 
                base(sourceLineNumbers, id, resourceName, messageArgs)
        {
        }
        
        public override ResourceManager ResourceManager
        {
            get
            {
                return resourceManager;
            }
        }
    }
    
    public sealed class ValidationWarnings
    {
        
        private ValidationWarnings()
        {
        }
        
        public static ValidationWarningEventArgs ExampleWarning(SourceLineNumberCollection sourceLineNumbers)
        {
            return new ValidationWarningEventArgs(sourceLineNumbers, 6599, "ValidationWarnings_ExampleWarning_1");
        }
        
        public static ValidationWarningEventArgs AnotherExampleWarning(SourceLineNumberCollection sourceLineNumbers)
        {
            return new ValidationWarningEventArgs(sourceLineNumbers, 6598, "ValidationWarnings_AnotherExampleWarning_1");
        }
    }
}
